### ISSUE TITLE
Subscribe Overlay

### ISSUE THREAD

**Issue by KevRM** [CitizensBudgetCommission/cbcny-d8#202]
To improve likelihood of capturing email addresses from visitors who are not already subscribers, we would like to explore an overlay popup that asks a visitor--who has meaningfully engaged with our content--to subscribe to our content.

It is important to review our current subscribe page and make recommendations on how the overlay and subscribe page comport with each other.

**Comment by peterserfozo** [comment]
@KevRM  I think we should keep the current subscribe form and buttons. Besides that, I can create an overlay popup containing only a Subscribe button points to the subscribe form and some text.
I can add different triggers to display the popup, for example, display after time spent on the website or a scrolling trigger.

The other option is removing the current subscribe implementation and use a 3rd party solution for collecting the emails, displaying the popup, and build a subscribe form. For example, see https://www.poptin.com/
Of course, most of these services are not free.

**Comment by bjoseph33** [comment]
@joshua1234511, here is feedback from @KevRM.  

1. Please remove the title of "Subscribe" in the overlay.  Only have the text and button (that says "Subscribe").
2. Please limit the overlay to only display when the user navigates to "Research" or "Advocacy" sections.
3. Limit width of overlay.  Text can wrap to two lines.  Then center "Subscribe" button.
4. If possible, please have overlay fade in or display a bit slower.

**Comment by joshua1234511** [comment]
@bjoseph33 

Please remove the title of "Subscribe" in the overlay. Only have the text and button (that says "Subscribe").
-- Done
Please limit the overlay to only display when the user navigates to "Research" or "Advocacy" sections.
-- Done, Will only show on the mentioned pages
Limit width of overlay. Text can wrap to two lines. Then center "Subscribe" button.
-- Done
If possible, please have overlay fade in or display a bit slower.
-- Done, Animation added
Screencast: https://nimb.ws/OjZFKg

PR raised and assigned for review
Can be tested on dev https://dev-cbcny.pantheonsite.io/

Once code review approved will merge to master and then will be available on test environment
