### ISSUE TITLE
Breaks between paragraphs of bullet lists do not work

### ISSUE THREAD

**Issue by KevRM** [CitizensBudgetCommission/cbcny-d8#222]
https://cbcny.org/advocacy/testimony-comprehensive-long-term-planning-intro-2186

On this page, you'll see some paragraphs between bullet points are not breaking, despite break tags in the source of the full-text paragraph type.

It might be useful to review the format style ordered and unordered lists

**Comment by joshua1234511** [comment]
Breaks between paragraphs of bullet lists do not work
https://github.com/CitizensBudgetCommission/cbcny-d8/issues/222
Issue: Incorrect html used. NO <p> tag used
https://nimb.ws/SOYj0a
Fixed-- Added correct text html on test: 
https://cbcny.org/advocacy/testimony-comprehensive-long-term-planning-intro-2186
https://nimb.ws/L1apSr
