### ISSUE TITLE
Security & Drupal module updates

### ISSUE THREAD

**Issue by bjoseph33** [CitizensBudgetCommission/cbcny-d8#228]

**Comment by bjoseph33** [comment]
@danyg79 please also look at the security alert sent by Dependabot (Security > Dependabot alerts > node-sass).

**Comment by danyg79** [comment]
@KevRM site has been updated and can be tested at  https://test-cbcny.pantheonsite.io/
I wasn't able to update Search API Solr to 8.x-1.10. It requires the SearchApiPantheon and the upgrade of Solarium to v6.1.1, but it has an issue with arguments. I found a ticket of it: https://www.drupal.org/project/search_api_pantheon/issues/3197199 and it suggested not to update the Search API Solr to this version.
@bjoseph33 can you add more details to the Security alert you've mentioned? I can't reach the path you've written, maybe this is what you thought? https://github.com/CitizensBudgetCommission/cbcny-d8/pull/205

**Comment by bjoseph33** [comment]
@danyg79 here are screenshots of the error messages.  Please review and let us know what is needed for remediation.

![197098FA-BE89-4235-8BDD-8A504B0E5405](https://user-images.githubusercontent.com/60715992/116255456-43130e80-a740-11eb-9535-d862b1620ae7.jpeg)
![11918A14-C2AC-4D03-AE62-B891CE3CB82D](https://user-images.githubusercontent.com/60715992/116255459-43aba500-a740-11eb-950c-56fe272ddf98.jpeg)

**Comment by danyg79** [comment]
@bjoseph33 thanks for the screens, I'll take a look at them. But it would be useful if I will have access to that menu (I can't see that submenu under Security). Can you give me the necessary permissions?

**Comment by danyg79** [comment]
@bjoseph33 pear/archive has a new release since Feb, 2021 (https://github.com/pear/Archive_Tar/releases/tag/1.4.13)
The link to this package in in Drupal Core (https://git.drupalcode.org/project/drupal/-/blob/8.9.x/core/composer.json#L49) and I couldn't see request to update it yet.
The node-sass is in the theme package and we may try to upgrade it, but actually the used theme has some critical updates in the top of that (see https://nimb.ws/Thjn5p). If we update the node-sass package we should do some manual tests to check if  everything works as expected.

**Comment by bjoseph33** [comment]
@KevRM  please see Daniel's comments above.  Can you grant him additional privileges so he can view the security alerts?  Additionally, it seems as if the pear/archive.tar is not a concern at this time.  Are you OK with the additional level of manual testing required for the node-sass updates?

**Comment by KevRM** [comment]
Benny, an invitation was sent to Daniel. 

Yes, I am OK with additional testing.

**Comment by danyg79** [comment]
.Core upgrade (to 8.9.14), Ctools, Inline Entity For.m module upgrades have been released to Production.)
Meantime there is a new version of Drupal Core (8.9.15) and Webform (8.x-5.26). Should I do those updates within this issue or will we create a new one for those?

**Comment by danyg79** [comment]
@KevRM Unfortunately, the upgrade of the theme to the recent version (8.3.x) cannot be done without major issues. 
However I was able to update the node-sass package to the desired version 4.13.1. I can't see any issues. The changes were released on Test environment, please check it at https://test-cbcny.pantheonsite.io/

**Comment by KevRM** [comment]
This is OK to go live

**Comment by danyg79** [comment]
@KevRM All updates have been deployed to Production.
