### ISSUE TITLE
Off Cycle Core Update

### ISSUE THREAD

**Issue by KevRM** [CitizensBudgetCommission/cbcny-d8#233]

**Comment by danyg79** [comment]
@KevRM Drupal Core has been updated and can be tested at https://dev-cbcny.pantheonsite.io/
Besides the Core update I've also updated the following modules:
Ctools module 3.5.0 => 3.6.0 (security update)
Facets module 1.7.0 => 1.8.0 (security update)
Webform module 5.25.0 => 5.26.0
Devel module 1.2.0 => 4.1.1

Please take a look at them and inform us if there is any problem with the updates or we can move the updates forward to test and prod environments.

**Comment by KevRM** [comment]
Looks good, you can go live with changes when you can (if you can't do it today, let's wait until tomorrow afternoon/evening).

**Comment by danyg79** [comment]
@KevRM Updates were released to LIVE today afternoon. I clicked through the site, it seems everything is OK.

**Comment by danyg79** [comment]
For some reason these updates were revoked and disappeared from the LIVE version of cbcny.org. 
During last development and deployment (Energy & Environment) I pulled codebase/database from LIVE to DEV and TEST, so changes disappeared from there too. 
I reopen this issue, and will do existing updates of Drupal Core and contrib modules and try to deploy them again.

**Comment by danyg79** [comment]
Finally these updates were deployed to LIVE again (I don't understand why this issue has happened). The updates works as expected in all three environments.
