### ISSUE TITLE
cbcny.org affected by Fastly disruption

### ISSUE THREAD

**Issue by KevRM** [CitizensBudgetCommission/cbcny-d8#234]
On June 8th cbcny.org went down during the Fastly disruption (503 error).    According to UptimeRobot:
- DOWN 2021-06-08 10:11:54 UTC+0
-UP 2021-06-08 10:16:48 UTC+0

That totals to 5 minutes, however beyond that window I did receive 503 errors on pages clicked after the initial landing page (ex. homepage loaded, but click to next page led to a 503). This may have lasted for a total of 20 minutes, maybe longer.

cbcny.org does not use Fastly as its CDN (we pay for Cloudflare). However,  Pantheon's CDN service is powered by Fastly.

Can this be investigated, and can you share with the team why cbcny.org went down during Fastly? Was the relatively short downtime compared to other websites thanks to Cloudflare? Does having both Pantheon and Cloudflare explain why I had intermittent access to the homepage, but 503'd when I tried to load a new page?

Also, is it possible to better configure both the Pantheon and Cloudflare to ensure redundancy?

**Comment by danyg79** [comment]
drupal.org was also affected by this disruption (see posts from 8th of June at https://twitter.com/drupal_infra)

**Comment by danyg79** [comment]
Here is a summary of the outage from the side of Fastly: https://www.fastly.com/blog/summary-of-june-8-outage
Unfortunately, I didn't find an explanation on behalf of Pantheon, but there were many reports, articles with this outage
https://www.theguardian.com/technology/2021/jun/08/edge-cloud-error-tuesday-internet-outage-fastly-speed
https://screenrant.com/internet-outage-june-2021-fastly-cdn-down-what-why/
https://techcrunch.com/2021/06/08/numerous-popular-websites-are-facing-an-outage/
