### ISSUE TITLE
New Topic to add to topic taxonomy

### ISSUE THREAD

**Issue by KevRM** [CitizensBudgetCommission/cbcny-d8#235]
Please add a new topic to the taxonomy called Energy & Environment. I will attach to this issue a png graphic of what the icon should look like. Please tell me what kind of files you needs to add this icon to the topic (what kind of files, colors, etc.)

**Comment by KevRM** [comment]
![Environment and Energy icon-01](https://user-images.githubusercontent.com/13575650/125697727-f45951de-4a2e-4b55-bdba-70ca4d5cba2e.png)

This is the icon. Let me know how I should share this with you (presently a PNG with transparent background)

**Comment by danyg79** [comment]
@KevRM The update has been done and can be checked at https://dev-cbcny.pantheonsite.io/
We made SVG images from the PNG you've provided.

(I'm available only tomorrow before my vacation, therefore I can do a release to the Live only tomorrow or we will ask somebody else at Cheppers to do so.)

**Comment by KevRM** [comment]
This is good to go!!

**Comment by danyg79** [comment]
@KevRM the updates have been deployed to LIVE: https://cbcny.org/topics/energy-environment
